"""v1 initial schema

Revision ID: c9b7a7b60da5
Revises:
Create Date: 2026-08-25 13:03:11.445655
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c9b7a7b60da5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "v1_admin_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("login_name", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "suspended", "archived", name="adminstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login_name"),
    )
    op.create_index(
        "ix_admin_accounts_login_name", "v1_admin_accounts", ["login_name"], unique=False
    )
    op.create_table(
        "v1_operation_audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("target_type", sa.String(length=30), nullable=True),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("metadata", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "v1_teacher_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("login_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "archived", name="teacherstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login_name"),
    )
    op.create_index(
        "ix_teacher_accounts_login_name", "v1_teacher_accounts", ["login_name"], unique=False
    )
    op.create_table(
        "v1_access_codes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code_digest", sa.String(length=64), nullable=False),
        sa.Column("display_tail", sa.String(length=5), nullable=False),
        sa.Column("created_by_teacher_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("redeem_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeem_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_teacher_id"],
            ["v1_teacher_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_digest"),
        sa.UniqueConstraint(
            "created_by_teacher_id", "idempotency_key", name="uq_access_codes_teacher_intent"
        ),
    )
    op.create_index("ix_access_codes_code_digest", "v1_access_codes", ["code_digest"], unique=False)
    op.create_table(
        "v1_admin_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admin_id", sa.String(length=36), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["v1_admin_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_admin_sessions_admin_id", "v1_admin_sessions", ["admin_id"], unique=False)
    op.create_index(
        "ix_admin_sessions_token_digest", "v1_admin_sessions", ["token_digest"], unique=False
    )
    op.create_table(
        "v1_rights_attestations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("statement_version", sa.String(length=30), nullable=False),
        sa.Column("teacher_id", sa.String(length=36), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=True),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("attested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["v1_teacher_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "v1_teacher_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("teacher_id", sa.String(length=36), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["v1_teacher_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_teacher_sessions_teacher_id", "v1_teacher_sessions", ["teacher_id"], unique=False
    )
    op.create_index(
        "ix_teacher_sessions_token_digest", "v1_teacher_sessions", ["token_digest"], unique=False
    )
    op.create_table(
        "v1_trial_followups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("feishu_record_ref", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("teacher_id", sa.String(length=36), nullable=True),
        sa.Column("updated_by_admin_id", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["updated_by_admin_id"],
            ["v1_admin_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feishu_record_ref"),
    )
    op.create_table(
        "v1_workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_teacher_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_teacher_id"],
            ["v1_teacher_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_teacher_id"),
    )
    op.create_index(
        "ix_workspaces_owner_teacher_id", "v1_workspaces", ["owner_teacher_id"], unique=False
    )
    op.create_table(
        "v1_courses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", "delivery_paused", name="coursestatus"),
            nullable=False,
        ),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["v1_workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_courses_status", "v1_courses", ["status"], unique=False)
    op.create_index("ix_courses_workspace_id", "v1_courses", ["workspace_id"], unique=False)
    op.create_table(
        "v1_redemptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("access_code_id", sa.String(length=36), nullable=False),
        sa.Column("local_identity_digest", sa.String(length=64), nullable=False),
        sa.Column("local_proof_digest", sa.String(length=64), nullable=False),
        sa.Column("first_redeemed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_redeemed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope_summary", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_code_id"],
            ["v1_access_codes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "access_code_id", "local_identity_digest", name="uq_redemptions_code_identity"
        ),
    )
    op.create_index(
        "ix_redemptions_local_identity", "v1_redemptions", ["local_identity_digest"], unique=False
    )
    op.create_table(
        "v1_course_releases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("release_number", sa.Integer(), nullable=False),
        sa.Column("source_course_revision", sa.Integer(), nullable=False),
        sa.Column("publish_intent_id", sa.String(length=64), nullable=False),
        sa.Column("course_title", sa.String(length=255), nullable=False),
        sa.Column("course_description", sa.String(length=2000), nullable=True),
        sa.Column("lesson_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "available", "superseded", "archived", name="releasestatus"),
            nullable=False,
        ),
        sa.Column("rights_attestation_id", sa.String(length=36), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_by_teacher_id", sa.String(length=36), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["v1_courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by_teacher_id"],
            ["v1_teacher_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rights_attestation_id"],
            ["v1_rights_attestations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "publish_intent_id", name="uq_releases_course_intent"),
        sa.UniqueConstraint("course_id", "release_number", name="uq_releases_course_number"),
    )
    op.create_index("ix_releases_course_id", "v1_course_releases", ["course_id"], unique=False)
    op.create_index("ix_releases_status", "v1_course_releases", ["status"], unique=False)
    op.create_table(
        "v1_grant_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("access_code_id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("scope_data", sa.JSON(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["access_code_id"],
            ["v1_access_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["v1_courses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "access_code_id", "course_id", "scope", name="uq_grants_code_course_scope"
        ),
    )
    op.create_index(
        "ix_grant_items_access_code_id", "v1_grant_items", ["access_code_id"], unique=False
    )
    op.create_index("ix_grant_items_course_id", "v1_grant_items", ["course_id"], unique=False)
    op.create_table(
        "v1_lessons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["v1_courses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "sequence", name="uq_lessons_course_sequence"),
    )
    op.create_index("ix_lessons_course_id", "v1_lessons", ["course_id"], unique=False)
    op.create_table(
        "v1_release_availability",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=50), nullable=False),
        sa.Column("scope_data", sa.JSON(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated", sa.Boolean(), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_reason", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["v1_course_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("release_id"),
    )
    op.create_index(
        "ix_availability_release_id", "v1_release_availability", ["release_id"], unique=False
    )
    op.create_table(
        "v1_release_lesson_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_sequence", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_title", sa.String(length=255), nullable=False),
        sa.Column("lesson_revision", sa.Integer(), nullable=False),
        sa.Column("lesson_description", sa.String(length=2000), nullable=True),
        sa.Column("video_platform", sa.String(length=50), nullable=False),
        sa.Column("video_platform_id", sa.String(length=255), nullable=False),
        sa.Column("nodes", sa.JSON(), nullable=False),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["v1_lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["v1_course_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("release_id", "lesson_sequence", name="uq_snapshots_release_sequence"),
    )
    op.create_index(
        "ix_snapshots_release_id", "v1_release_lesson_snapshots", ["release_id"], unique=False
    )
    op.create_table(
        "v1_script_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lesson_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.String(length=10), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("saved_by_teacher_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["v1_lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["saved_by_teacher_id"],
            ["v1_teacher_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id"),
    )
    op.create_index("ix_script_drafts_lesson_id", "v1_script_drafts", ["lesson_id"], unique=False)
    op.create_index(
        "ix_script_drafts_teacher_id", "v1_script_drafts", ["saved_by_teacher_id"], unique=False
    )
    op.create_table(
        "v1_video_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lesson_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_video_id", sa.String(length=255), nullable=False),
        sa.Column("start_time_seconds", sa.Integer(), nullable=True),
        sa.Column("end_time_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["v1_lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id"),
    )
    op.create_index(
        "ix_video_references_lesson_id", "v1_video_references", ["lesson_id"], unique=False
    )
    op.create_index(
        "ix_video_references_platform_id",
        "v1_video_references",
        ["platform", "platform_video_id"],
        unique=False,
    )
    op.create_table(
        "v1_preview_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("teacher_id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_id", sa.String(length=36), nullable=False),
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("locked_content", sa.JSON(), nullable=True),
        sa.Column("contract_version", sa.String(length=30), nullable=False),
        sa.Column("plugin_version", sa.String(length=30), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=True),
        sa.Column("error_category", sa.String(length=60), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["v1_courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["v1_script_drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["v1_lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["v1_teacher_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_preview_sessions_lesson_id", "v1_preview_sessions", ["lesson_id"], unique=False
    )
    op.create_index(
        "ix_preview_sessions_teacher_id", "v1_preview_sessions", ["teacher_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("v1 不支持降级；开发阶段重建空数据库")
